web-mongo:
    build: ../web-mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
        - MONGO_INITDB_DATABASE
    ports:
        - "27017:27017"
    command: mongod

application-service:
    build: ../application-service
    environment:
        - NODE_ENV=production
        - MONGO_HOST
        - MONGO_USER
        - MONGO_PASS
    ports:
        - "3000:3000"
    links:
        - web-mongo


application-admin:
    build: ../application-admin
    environment:
      - NODE_ENV=production
    ports:
        - "4300:4200"
    links:
      - application-service

application-form:
    build: ../application-form
    environment:
      - NODE_ENV=production
    ports:
        - "4200:4200"
    links:
      - application-service

nginx:
    build: ./
    ports:
        - "80:80"
    links:
      - application-service